theme: jekyll-theme-minimal
title: CS-358 - Making Intelligent Things
description: Course Website 2023
#show_downloads: False
#navigation:
#  - title: Home
#    url: /
#  - title: Bibliography
#    url: bibliography
#  - title: Project 1 individual
#    url: example
